export const dataProduct = [ 
    {
        id:0,
        name:'NIKE ZOOM KD 12 UNIVERSITY RED',
        typeName:'BASKETBALL SHOES',
        price:140,
        priceDiscount:130,
        brand:'KD',
        linkImage:'https://it.basketzone.net/zdjecia/2019/06/18/306/59/NIKE_ZOOM_KD_12_UNIVERSITY_REDs-mini.jpg',
        type:1,
    },
    {
        id:1,
        name:'NIKE KYRIE FLYTRAP III SOUTH BEACH',
        typeName:'BASKETBALL SHOES',
        price:100,
        priceDiscount:null,
        brand:'KYRIE',
        linkImage:'https://sk.basketzone.net/zdjecia/2020/07/31/207/37/NIKE_KYRIE_FLYTRAP_III_SOUTH_BEACHs-mini.jpg?mini',
        type:1,
    },
    {
        id:2,
        name:'NIKE LEBRON 18 MULTICOLOR',
        typeName:'BASKETBALL SHOES',
        price:100,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://basketzone.net/zdjecia/2020/11/11/211/21/NIKE_LEBRON_18_MULTICOLORs-mini.jpg?mini',
        type:1,
    },
    {
        id:3,
        name:'NIKE AIR JORDAN 3 RETRO CHLOROPHYLL TINKER',
        typeName:'BASKETBALL SHOES',
        price:220,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://it.basketzone.net/zdjecia/2018/12/05/412/24/AIR_JORDAN_3_RETROs-mini.jpg?mini',
        type:1,
    },
    {
        id:4,
        name:'NIKE KYRIE LOW 3 TIE DYE',
        typeName:'BASKETBALL SHOES',
        price:110,
        priceDiscount:null,
        brand:'KYRIE',
        linkImage:'https://fr.kicksmaniac.com/zdjecia/2020/09/22/1209/25/NIKE_KYRIE_LOW_3_TIE_DYEs-mini.jpg?mini',
        type:1,
    },
    {
        id:5,
        name:'NIKE LEBRON 17 LOW GLOW IN THE DARK',
        typeName:'BASKETBALL SHOES',
        price:150,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://tr.basketzone.net/zdjecia/2020/09/22/1209/17/NIKE_LEBRON_17_LOW_GLOW_IN_THE_DARKs-mini.jpg?mini',
        type:1,
    },
    {
        id:6,
        name:'NIKE AIR JORDAN MAX AURA 2 COOL GREY',
        typeName:'BASKETBALL SHOES',
        price:110,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://de.basketzone.net/zdjecia/2021/01/21/401/47/NIKE_AIR_JORDAN_MAX_AURA_2_COOL_GREYs-mini.jpg?mini',
        type:1,
    },
    {
        id:7,
        name:'NIKE AIR JORDAN MAX AURA 2 BRED',
        price:150,
        typeName:'BASKETBALL SHOES',
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://kicksmaniac.com/zdjecia/2020/12/16/412/25/NIKE_AIR_JORDAN_MAX_AURA_2_BREDs-mini.jpg?mini',
        type:1,
    },
    {
        id:8,
        name:'NIKE AIR JORDAN 1 RETRO MID UNION BLACK TOE',
        typeName:'BASKETBALL SHOES',
        price:220,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://basketzone.pl/zdjecia/2020/09/04/509/49/NIKE_AIR_JORDAN_1_RETRO_MID_UNION_BLACK_TOEs-mini.jpg?mini',
        type:1,
    },
    {
        id:9,
        name:'NIKE KYRIE FLYTRAP II DUKE BLUE DEVILS',
        typeName:'BASKETBALL SHOES',
        price:95,
        priceDiscount:80,
        brand:'KYRIE',
        linkImage:'https://hu.basketzone.net/zdjecia/2019/08/01/1108/54/NIKE_KYRIE_FLYTRAP_II_DUKE_BLUE_DEVILSs-mini.jpg?mini',
        type:1,
    },
    {
        id:10,
        name:'NIKE ZOOM KD 13 NETS HARDWOOD CLASSICS',
        typeName:'BASKETBALL SHOES',
        price:145,
        priceDiscount:null,
        brand:'KD',
        linkImage:'https://it.basketzone.net/zdjecia/2020/12/16/312/35/NIKE_ZOOM_KD_13_HARDWOOD_CLASSICSs-mini.jpg?mini',
        type:1,
    },
    {
        id:11,
        name:'NIKE KYRIE 6 USA OLYMPIC TEAM',
        typeName:'BASKETBALL SHOES',
        price:120,
        priceDiscount:110,
        brand:'KYRIE',
        linkImage:'https://cz.basketzone.net/zdjecia/2020/09/10/1209/07/NIKE_KYRIE_6_USA_OLYMPIC_TEAMs-mini.jpg?mini',
        type:1,
    },
    {
        id:12,
        name:'NIKE AIR JORDAN SPORTSWEAR WINGS FLEECE HOODIE BLACK',
        typeName:'HOODIES',
        price:80,
        priceDiscount:65,
        brand:'JORDAN',
        linkImage:'https://kicksmaniac.com/zdjecia/2017/07/20/407/25/NIKE_AIR_JORDAN_SPORTSWEAR_WINGS_FLEECE_HOODIE_BLACKs-mini.jpg?mini',
        type:2,
    },
    {
        id:13,
        name:'NIKE AIR JORDAN SPORTSWEAR JUMPMAN AIR EMBROIERED TEE GUM RED',
        typeName:'T-SHIRTS',
        price:30,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://nl.kicksmaniac.com/zdjecia/2018/01/15/401/17/M_JSW_TEE_JMPMN_AIR_EMBRDs-mini.jpg?mini',
        type:2,
    },
    {
        id:14,
        name:'NIKE NBA LOS ANGELES LAKERS PRACTICE SHORTS FIELD PURPLE',
        typeName:'T-SHORTS',
        price:45,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://basketzone.pl/zdjecia/2018/09/10/809/57/NIKE_NBA_LOS_ANGELES_LAKERS_PRACTICE_SHORTS_FIELD_PURPLEs-mini.jpg?mini',
        type:2,
    },
    {
        id:15,
        name:'NIKE NBA MILWAUKEE BUCKS GIANNIS ANTETOKOUNMPO SWINGMAN JERSEY SUNDIAL',
        typeName:'T-SHIRTS',
        price:80,
        priceDiscount:75,
        brand:'ANTETOKOUNMPO',
        linkImage:'https://de.basketzone.net/zdjecia/2018/12/11/1112/25/NIKE_NBA_MILWAUKEE_BUCKS_GIANNIS_ANTETOKOUNMPO_SWINGMAN_JERSEY_SUNDIALs-mini.jpg?mini',
        type:2,
    },
    {
        id:16,
        name:'NIKE JORDAN DRI-FIT NO-SHOW 3PK SOCKS',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://basketzone.net/zdjecia/zdjecia/2015/04/03/NIKE_JORDAN_DRI-FIT_NO-SHOW_3PK_SOCKS_546479-012-mini.jpg?mini',
        type:2,
    },
    {
        id:17,
        name:'NIKE AIR JORDAN EVERYDAY WATERFALL SOCKS BLACK',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://kicksmaniac.com/zdjecia/2019/10/14/1010/08/NIKE_AIR_JORDAN_EVERYDAY_WATERFALL_SOCKS_BLACKs-mini.jpg?mini',
        type:2,
    },
    {
        id:18,
        name:'NIKE AIR JORDAN EVERYDAY WATERFALL SOCKS WHITE',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://fr.basketzone.net/zdjecia/2018/07/16/907/54/NIKE_AIR_JORDAN_EVERYDAY_WATERFALL_SOCKS_WHITEs-mini.jpg?mini',
        type:2,
    },
    {
        id:19,
        name:'NIKE AIR JORDAN JUMPMAN NO-SHOW SOCKS BLACK',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://se.basketzone.net/zdjecia/2017/09/07/1009/00/NIKE_AIR_JORDAN_JUMPMAN_NO_SHOW_SOCKS_BLACKs-mini.jpg?mini',
        type:2,
    },
    {
        id:20,
        name:'NIKE AIR JORDAN JUMPMAN NO-SHOW SOCKS BLACK WHITE GYM RED',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://dk.basketzone.net/zdjecia/2017/04/20/904/42/NIKE_AIR_JORDAN_JUMPMAN_NO_SHOW_SOCKS_BLACK_WHITE_GYM_REDs-mini.jpg?mini',
        type:2,
    },
    {
        id:21,
        name:'NIKE NBA GOLDEN STATE WARRIOS KEVIN DURANT SWINGMAN JERSEY ROAD',
        typeName:'T-SHIRTS',
        price:75,
        priceDiscount:65,
        brand:'KD',
        linkImage:'https://sk.basketzone.net/zdjecia/2017/12/04/412/32/NIKE_NBA_GOLDEN_STATE_WARRIORS_KEVIN_DURANT_SWINGMAN_JERSEY_ROAD__RUSH_BLUEs-mini.jpg?mini',
        type:2,
    }
];