import player1 from "./Assets/Images/Player/koszykarze_1.png"
import player2 from "./Assets/Images/Player/koszykarze_2.png"
import player3 from "./Assets/Images/Player/koszykarze_3.png"
import player4 from "./Assets/Images/Player/koszykarze_4.png"
import player5 from "./Assets/Images/Player/koszykarze_5.png"
import player6 from "./Assets/Images/Player/koszykarze_6.png"
import player7 from "./Assets/Images/Player/koszykarze_11.png"
import player8 from "./Assets/Images/Player/koszykarze_10.png"
import player9 from "./Assets/Images/Player/koszykarze_9.png"
import player10 from "./Assets/Images/Player/koszykarze_8.png"
export const dataProduct = [ 
    {
        id:0,
        name:'NIKE ZOOM KD 12 UNIVERSITY RED',
        typeName:'BASKETBALL SHOES',
        price:140,
        priceDiscount:130,
        brand:'KD',
        linkImage:'https://it.basketzone.net/zdjecia/2019/06/18/306/59/NIKE_ZOOM_KD_12_UNIVERSITY_REDs-mini.jpg',
        type:1,
    },
    {
        id:1,
        name:'NIKE KYRIE FLYTRAP III SOUTH BEACH',
        typeName:'BASKETBALL SHOES',
        price:100,
        priceDiscount:null,
        brand:'KYRIE',
        linkImage:'https://sk.basketzone.net/zdjecia/2020/07/31/207/37/NIKE_KYRIE_FLYTRAP_III_SOUTH_BEACHs-mini.jpg?mini',
        type:1,
    },
    {
        id:2,
        name:'NIKE LEBRON 18 MULTICOLOR',
        typeName:'BASKETBALL SHOES',
        price:100,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://basketzone.net/zdjecia/2020/11/11/211/21/NIKE_LEBRON_18_MULTICOLORs-mini.jpg?mini',
        type:1,
    },
    {
        id:3,
        name:'NIKE AIR JORDAN 3 RETRO CHLOROPHYLL TINKER',
        typeName:'BASKETBALL SHOES',
        price:220,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://it.basketzone.net/zdjecia/2018/12/05/412/24/AIR_JORDAN_3_RETROs-mini.jpg?mini',
        type:1,
    },
    {
        id:4,
        name:'NIKE KYRIE LOW 3 TIE DYE',
        typeName:'BASKETBALL SHOES',
        price:110,
        priceDiscount:null,
        brand:'KYRIE',
        linkImage:'https://fr.kicksmaniac.com/zdjecia/2020/09/22/1209/25/NIKE_KYRIE_LOW_3_TIE_DYEs-mini.jpg?mini',
        type:1,
    },
    {
        id:5,
        name:'NIKE LEBRON 17 LOW GLOW IN THE DARK',
        typeName:'BASKETBALL SHOES',
        price:150,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://tr.basketzone.net/zdjecia/2020/09/22/1209/17/NIKE_LEBRON_17_LOW_GLOW_IN_THE_DARKs-mini.jpg?mini',
        type:1,
    },
    {
        id:6,
        name:'NIKE AIR JORDAN MAX AURA 2 COOL GREY',
        typeName:'BASKETBALL SHOES',
        price:110,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://de.basketzone.net/zdjecia/2021/01/21/401/47/NIKE_AIR_JORDAN_MAX_AURA_2_COOL_GREYs-mini.jpg?mini',
        type:1,
    },
    {
        id:7,
        name:'NIKE AIR JORDAN MAX AURA 2 BRED',
        price:150,
        typeName:'BASKETBALL SHOES',
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://kicksmaniac.com/zdjecia/2020/12/16/412/25/NIKE_AIR_JORDAN_MAX_AURA_2_BREDs-mini.jpg?mini',
        type:1,
    },
    {
        id:8,
        name:'NIKE AIR JORDAN 1 RETRO MID UNION BLACK TOE',
        typeName:'BASKETBALL SHOES',
        price:220,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://basketzone.pl/zdjecia/2020/09/04/509/49/NIKE_AIR_JORDAN_1_RETRO_MID_UNION_BLACK_TOEs-mini.jpg?mini',
        type:1,
    },
    {
        id:9,
        name:'NIKE KYRIE FLYTRAP II DUKE BLUE DEVILS',
        typeName:'BASKETBALL SHOES',
        price:95,
        priceDiscount:80,
        brand:'KYRIE',
        linkImage:'https://hu.basketzone.net/zdjecia/2019/08/01/1108/54/NIKE_KYRIE_FLYTRAP_II_DUKE_BLUE_DEVILSs-mini.jpg?mini',
        type:1,
    },
    {
        id:10,
        name:'NIKE ZOOM KD 13 NETS HARDWOOD CLASSICS',
        typeName:'BASKETBALL SHOES',
        price:145,
        priceDiscount:null,
        brand:'KD',
        linkImage:'https://it.basketzone.net/zdjecia/2020/12/16/312/35/NIKE_ZOOM_KD_13_HARDWOOD_CLASSICSs-mini.jpg?mini',
        type:1,
    },
    {
        id:11,
        name:'NIKE KYRIE 6 USA OLYMPIC TEAM',
        typeName:'BASKETBALL SHOES',
        price:120,
        priceDiscount:110,
        brand:'KYRIE',
        linkImage:'https://cz.basketzone.net/zdjecia/2020/09/10/1209/07/NIKE_KYRIE_6_USA_OLYMPIC_TEAMs-mini.jpg?mini',
        type:1,
    },
    {
        id:12,
        name:'NIKE AIR JORDAN SPORTSWEAR WINGS FLEECE HOODIE BLACK',
        typeName:'HOODIES',
        price:80,
        priceDiscount:65,
        brand:'JORDAN',
        linkImage:'https://kicksmaniac.com/zdjecia/2017/07/20/407/25/NIKE_AIR_JORDAN_SPORTSWEAR_WINGS_FLEECE_HOODIE_BLACKs-mini.jpg?mini',
        type:2,
    },
    {
        id:13,
        name:'NIKE AIR JORDAN SPORTSWEAR JUMPMAN AIR EMBROIERED TEE GUM RED',
        typeName:'T-SHIRTS',
        price:30,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://nl.kicksmaniac.com/zdjecia/2018/01/15/401/17/M_JSW_TEE_JMPMN_AIR_EMBRDs-mini.jpg?mini',
        type:2,
    },
    {
        id:14,
        name:'NIKE NBA LOS ANGELES LAKERS PRACTICE SHORTS FIELD PURPLE',
        typeName:'T-SHORTS',
        price:45,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://basketzone.pl/zdjecia/2018/09/10/809/57/NIKE_NBA_LOS_ANGELES_LAKERS_PRACTICE_SHORTS_FIELD_PURPLEs-mini.jpg?mini',
        type:2,
    },
    {
        id:15,
        name:'NIKE NBA MILWAUKEE BUCKS GIANNIS ANTETOKOUNMPO SWINGMAN JERSEY SUNDIAL',
        typeName:'T-SHIRTS',
        price:80,
        priceDiscount:75,
        brand:'ANTETOKOUNMPO',
        linkImage:'https://de.basketzone.net/zdjecia/2018/12/11/1112/25/NIKE_NBA_MILWAUKEE_BUCKS_GIANNIS_ANTETOKOUNMPO_SWINGMAN_JERSEY_SUNDIALs-mini.jpg?mini',
        type:2,
    },
    {
        id:16,
        name:'NIKE JORDAN DRI-FIT NO-SHOW 3PK SOCKS',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://basketzone.net/zdjecia/zdjecia/2015/04/03/NIKE_JORDAN_DRI-FIT_NO-SHOW_3PK_SOCKS_546479-012-mini.jpg?mini',
        type:2,
    },
    {
        id:17,
        name:'NIKE AIR JORDAN EVERYDAY WATERFALL SOCKS BLACK',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://kicksmaniac.com/zdjecia/2019/10/14/1010/08/NIKE_AIR_JORDAN_EVERYDAY_WATERFALL_SOCKS_BLACKs-mini.jpg?mini',
        type:2,
    },
    {
        id:18,
        name:'NIKE AIR JORDAN EVERYDAY WATERFALL SOCKS WHITE',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://fr.basketzone.net/zdjecia/2018/07/16/907/54/NIKE_AIR_JORDAN_EVERYDAY_WATERFALL_SOCKS_WHITEs-mini.jpg?mini',
        type:2,
    },
    {
        id:19,
        name:'NIKE AIR JORDAN JUMPMAN NO-SHOW SOCKS BLACK',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://se.basketzone.net/zdjecia/2017/09/07/1009/00/NIKE_AIR_JORDAN_JUMPMAN_NO_SHOW_SOCKS_BLACKs-mini.jpg?mini',
        type:2,
    },
    {
        id:20,
        name:'NIKE AIR JORDAN JUMPMAN NO-SHOW SOCKS BLACK WHITE GYM RED',
        typeName:'CLOTHING',
        price:15,
        priceDiscount:null,
        brand:'JORDAN',
        linkImage:'https://dk.basketzone.net/zdjecia/2017/04/20/904/42/NIKE_AIR_JORDAN_JUMPMAN_NO_SHOW_SOCKS_BLACK_WHITE_GYM_REDs-mini.jpg?mini',
        type:2,
    },
    {
        id:21,
        name:'NIKE NBA GOLDEN STATE WARRIOS KEVIN DURANT SWINGMAN JERSEY ROAD',
        typeName:'T-SHIRTS',
        price:75,
        priceDiscount:65,
        brand:'KD',
        linkImage:'https://sk.basketzone.net/zdjecia/2017/12/04/412/32/NIKE_NBA_GOLDEN_STATE_WARRIORS_KEVIN_DURANT_SWINGMAN_JERSEY_ROAD__RUSH_BLUEs-mini.jpg?mini',
        type:2,
    },
    {
        id:22,
        name:'NIKE AIR MAX 90 ESSENTIAL ALL BLACK',
        typeName:'SPORTS SHOES',
        price:130,
        priceDiscount:120,
        brand:'AIR',
        linkImage:'https://fr.basketzone.net/zdjecia/2018/02/02/802/01/NIKE_AIR_MAX_90_ESSENTIAL_ALL_BLACKs-mini.jpg?mini',
        type:3,
    },
    {
        id:23,
        name:'NIKE AIR SKYLON II NAVY',
        typeName:'SPORTS SHOES',
        price:95,
        priceDiscount:75,
        brand:'AIR',
        linkImage:'https://nl.kicksmaniac.com/zdjecia/2019/03/15/403/36/NIKE_AIR_SKYLON_II_ARMORY_NAVYs-mini.jpg?mini',
        type:3,
    },
    {
        id:24,
        name:'NIKE AIR MAX 90 ESSENTIAL WOLF GREY',
        typeName:'SPORTS SHOES',
        price:130,
        priceDiscount:null,
        brand:'AIR',
        linkImage:'https://sk.basketzone.net/zdjecia/2019/02/20/302/26/NIKE_AIR_MAX_90_ESSENTIAL_WOLF_GREYs-mini.jpg?mini',
        type:3,
    },
    {
        id:25,
        name:'NIKE AIR SKYLON II WHITE ORANGE BLUE',
        typeName:'SPORTS SHOES',
        price:95,
        priceDiscount:80,
        brand:'AIR',
        linkImage:'https://de.basketzone.net/zdjecia/2019/03/15/503/37/NIKE_AIR_SKYLON_IIs-mini.jpg?mini',
        type:3,
    },
    {
        id:26,
        name:'NIKE GRANDSTAND II WHITE',
        typeName:'SPORTS SHOES',
        price:80,
        priceDiscount:65,
        brand:'AIR',
        linkImage:'https://it.kicksmaniac.com/zdjecia/2019/03/27/403/31/NIKE_GRANDSTAND_II_WHITEs-mini.jpg?mini',
        type:3,
    },
    {
        id:27,
        name:'NEW BALANCE X-90 BURGUNDY',
        typeName:'SPORTS SHOES',
        price:110,
        priceDiscount:95,
        brand:'BALANCE',
        linkImage:'https://se.basketzone.net/zdjecia/2019/04/12/304/21/NEW_BALANCE_X_90_BURGUNDYs-mini.jpg?mini',
        type:3,
    },
    {
        id:28,
        name:'ADIDAS TUBULAR SHADOW',
        typeName:'SPORTS SHOES',
        price:90,
        priceDiscount:null,
        brand:'ADIDAS',
        linkImage:'https://dk.basketzone.net/zdjecia/2018/10/26/310/58/ADIDAS_TUBULAR_SHADOW_REDs-mini.jpg?mini',
        type:3,
    },
    {
        id:29,
        name:'NEW BALANCE 574 BURGUNDY',
        typeName:'SPORTS SHOES',
        price:80,
        priceDiscount:65,
        brand:'BALANCE',
        linkImage:'https://es.basketzone.net/zdjecia/2019/04/11/304/03/NEW_BALANCE_574_BURGUNDYs-mini.jpg?mini',
        type:3,
    },
    {
        id:30,
        name:'NEW BALANCE 373 BLACK',
        typeName:'SPORTS SHOES',
        price:65,
        priceDiscount:null,
        brand:'BALANCE',
        linkImage:'https://basketzone.net/zdjecia/2019/04/11/404/45/NEW_BALANCE_373_BLACKs-mini.jpg?mini',
        type:3,
    },
    {
        id:31,
        name:'NIKE AIR MAX 90 ESSENTIAL TRIPLE WHITE',
        typeName:'SPORTS SHOES',
        price:130,
        priceDiscount:120,
        brand:'BALANCE',
        linkImage:'https://es.basketzone.net/zdjecia/2019/03/27/403/33/NIKE_AIR_MAX_90_ESSENTIAL_TRIPLE_WHITEs-mini.jpg?mini',
        type:3,
    },
    {
        id:32,
        name:'NIKE LEBRON WITNESS V VOLT',
        typeName:'BASKETBALL SHOES',
        price:95,
        priceDiscount:85,
        brand:'LEBRON',
        linkImage:'https://it.kicksmaniac.com/zdjecia/2021/04/03/604/40/NIKE_LEBRON_WITNESS_V_VOLTs-mini.jpg?mini',
        type:1,
    },
    {
        id:33,
        name:'NIKE LEBRON WITNESS IV LAKERS',
        typeName:'BASKETBALL SHOES',
        price:95,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://es.basketzone.net/zdjecia/2019/10/04/110/26/NIKE_LEBRON_WITNESS_IV_LAKERSs-mini.jpg?mini',
        type:1,
    },
    {
        id:34,
        name:'NIKE LEBRON 17 LOW PARTICLE GREY',
        typeName:'BASKETBALL SHOES',
        price:150,
        priceDiscount:130,
        brand:'LEBRON',
        linkImage:'https://es.kicksmaniac.com/zdjecia/2020/09/22/1209/36/NIKE_LEBRON_17_LOW_PARTICLE_GREYs-mini.jpg?mini',
        type:1,
    },
    {
        id:35,
        name:'NIKE LEBRON 17 LOW TITAN',
        typeName:'BASKETBALL SHOES',
        price:150,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://ro.basketzone.net/zdjecia/2020/11/08/611/20/NIKE_LEBRON_17_LOW_TITANs-mini.jpg?mini',
        type:1,
    },
    {
        id:36,
        name:'NIKE LEBRON WITNESS V OREO',
        typeName:'BASKETBALL SHOES',
        price:95,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://it.basketzone.net/zdjecia/2020/12/06/412/33/NIKE_LEBRON_WITNESS_V_OREOs-mini.jpg?mini',
        type:1,
    },
    {
        id:37,
        name:'NIKE LEBRON WITNESS V BLACK LIGHT BLUE FURY',
        typeName:'BASKETBALL SHOES',
        price:95,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://dk.basketzone.net/zdjecia/2021/03/09/603/43/NIKE_LEBRON_WITNESS_V_BLACK_LIGHT_BLUE_FURYs-mini.jpg?mini',
        type:1,
    },
    {
        id:38,
        name:'NIKE NBA LOS ANGELES LAKERS LEBRON JAMES ASSOCIATION EDITION SWINGMAN JERSEY',
        typeName:'T-SHIRTS',
        price:85,
        priceDiscount:null,
        brand:'LEBRON',
        linkImage:'https://nl.kicksmaniac.com/zdjecia/2020/10/05/410/51/NIKE_NBA_LOS_ANGELES_LAKERS_LEBRON_JAMES_ASSOCIATION_EDITION_SWINGMAN_JERSEY_WHITEs-mini.jpg?mini',
        type:2,
    },
    {
        id:39,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO RED BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:110,
        brand:'GRIFFIN',
        linkImage:'https://fr.basketzone.net/zdjecia/2017/04/05/804/26/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_RED_BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    {
        id:40,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO BLUE BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:110,
        brand:'GRIFFIN',
        linkImage:'https://nl.kicksmaniac.com/zdjecia/2017/04/25/1204/37/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_BLUE_BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    {
        id:41,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO BRED BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:110,
        brand:'GRIFFIN',
        linkImage:'https://it.basketzone.net/zdjecia/2017/05/06/1105/49/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_BRED_BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    {
        id:42,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO WHITE BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:105,
        brand:'GRIFFIN',
        linkImage:'https://de.basketzone.net/zdjecia/2017/03/15/1003/10/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_WHITE_BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    {
        id:43,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO BULLS ALTERNATE BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:110,
        brand:'GRIFFIN',
        linkImage:'https://dk.basketzone.net/zdjecia/2017/04/24/304/35/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_BULLS_ALTERNATE_BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    {
        id:44,
        name:'NIKE AIR JORDAN SUPER.FLY 4 RED JACQUARD BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:145,
        priceDiscount:110,
        brand:'GRIFFIN',
        linkImage:'https://es.basketzone.net/zdjecia/zdjecia/2015/11/05/NIKE_AIR_JORDAN_SUPER.FLY_4_JACQUARD_BLAKE_GRIFFIN_812870-605-mini.jpg?mini',
        type:1,
    },
    {
        id:45,
        name:'NIKE AIR JORDAN SUPER.FLY 4 PO "RIO TEAL" BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:95,
        brand:'GRIFFIN',
        linkImage:'https://cz.basketzone.net/zdjecia/2016/04/09/804/57/NIKE_AIR_JORDAN_SUPER.FLY_4_PO___RIO_TEAL___BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    {
        id:46,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO BLACK METTALIC GOLD BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:115,
        brand:'GRIFFIN',
        linkImage:'https://hu.basketzone.net/zdjecia/2017/02/09/902/50/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_BLACK_METTALIC_GOLD_BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    {
        id:47,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO NAVY BLUE LIME BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:110,
        brand:'GRIFFIN',
        linkImage:'https://fr.kicksmaniac.com/zdjecia/2017/03/07/903/52/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_s-mini.jpg?minii',
        type:1,
    },
    {
        id:48,
        name:'NIKE AIR JORDAN SUPER.FLY 5 PO CONTRAST BLAKE GRIFFIN',
        typeName:'BASKETBALL SHOES',
        price:130,
        priceDiscount:100,
        brand:'GRIFFIN',
        linkImage:'https://nl.basketzone.net/zdjecia/2017/05/06/1105/40/NIKE_AIR_JORDAN_SUPER.FLY_5_PO_CONTRAST_BLAKE_GRIFFINs-mini.jpg?mini',
        type:1,
    },
    
];

export const dataPlayer = [
    {
        id:0,
        idType:'LEBRON',
        linkImage:player1
    },
    {
        id:1,
        idType:'GRIFFIN',
        linkImage:player2,
    },
    {
        id:2,
        idType:'GEORGE',
        linkImage:player3,
    },
    {
        id:3,
        idType:'KYRIE',
        linkImage:player4,
    },
    {
        id:4,
        idType:'BUTLER',
        linkImage:player5,
    },
    {
        id:5,
        idType:'WESTBROOK',
        linkImage:player6,
    },
    {
        id:6,
        idType:'ANTETOKOUNMPO',
        linkImage:player7,
    },
    {
        id:7,
        idType:'BRYANT',
        linkImage:player8,
    },
    {
        id:8,
        idType:'JORDAN',
        linkImage:player9,
    },
    {
        id:9,
        idType:'KD',
        linkImage:player10,
    }
]